### ISSUE TITLE
Flask-Venom and synchronous request/reply

### ISSUE THREAD

**Issue by nochristrequired** [biosustain/venom#10]
Hi,

Regarding Flask-Venom, the readme says it supports synchronous request/reply. I was just curious what the technical reason was for this and if it only applies to debug server.

We are interested in using Venom on AppEngine (standard environment, python27, multithreaded requests.) For this, we give Google the flask app context and they handle the requests / threading. Is there a technical reason why this would be synchronous? Because we don't want to have our instances under-utilizes.

Thanks!

**Comment by nochristrequired** [comment]
Hi, after doing some research, I found out that WSGI is synchronous. Flask is a WSGI framework. We can't use async code from within the Flask request handlers. This makes sense now.

We were thinking of using Venom to replace the use of protorpc.wsgi RPC server (which is pretty busted and not well maintained.) AppEngine standard environment has multiple threads (I believe it is 8 threads per instance), but it still requires the use of WSGI, so long running RPC methods would block after 8 requests. After thinking about it, it would be much better suited for a task queue and callback url. 

It would still be nice to use Venom messages if they are easy to serialize / deserialize to/from JSON and to/from dict and if they support validation.

**Comment by lyschoening** [comment]
Hi @nochristrequired There's also an aiohttp implementation for Venom, but if you're stuck with WSGI you're out of luck. Venom will also never support Python 2. There is a JSON converter for Venom messages with type checking and conversion from/to dict is trivial. Validation of values / bounds checking is not there yet, but will be added soon.
